- hosts: all
  tasks:
    - name: Install multiple packages
      yum:
        name:
          - git
          - tree
          - maven
          - httpd  # (httpd equivalent in Debian)
          - docker
        state: present

