- hosts: all
  tasks:
    - name: Installing Docker on Redhat
      yum: 
        pkg: docker
        state: present
      when: ansible_os_family == "RedHat"

    - name: Installing Dokcer on Ubuntu
      apt:
        pkg: docker
        state: present
      when: ansible_os_family == "Ubuntu"

