- hosts: all
  tasks:
    - name: Installing NumPy
      pip:
        name: NumPy
        state: present

- hosts: all
  tasks:
    - name: Installing Pandas
      pip:
        name: Pandas
        state: present
